// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorCare.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotorCare.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509201214_AddPublicRecordAccesses")]
    partial class AddPublicRecordAccesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotorCare.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Plate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "StartAt");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MotorCare.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Phone")
                        .IsUnique()
                        .HasFilter("\"Phone\" IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MotorCare.Domain.Inspections.MotorcycleInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CosmeticNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GeneralNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("InspectionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("MileageQuery")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PackagePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Query5664")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TestRideNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "InspectionNo")
                        .IsUnique();

                    b.ToTable("MotorcycleInspections");
                });

            modelBuilder.Entity("MotorCare.Domain.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinimumStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasFilter("\"Sku\" IS NOT NULL");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("MotorCare.Domain.PublicRecords.PublicRecordAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("RecordType", "RecordId")
                        .IsUnique();

                    b.HasIndex("TenantId", "RecordType");

                    b.ToTable("PublicRecordAccesses", (string)null);
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ConsumableCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Specification")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category", "Brand", "ProductName")
                        .IsUnique();

                    b.ToTable("ConsumableCatalogItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("875bb55c-98fb-809d-768c-3be2795d7227"),
                            Brand = "Motul",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Günlük kullanım / performans / street",
                            ProductName = "7100 10W-40 4T",
                            Specification = "API SP, JASO MA2",
                            SubCategory = "4T Tam Sentetik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f7ff63a3-1525-cc8f-c375-b3fc9d4c1afc"),
                            Brand = "Motul",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Düşük viskozite isteyen modeller",
                            ProductName = "7100 10W-30 4T",
                            Specification = "API SP, JASO MA2",
                            SubCategory = "4T Tam Sentetik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("74df8308-8b94-16ba-69a7-df89876afdf0"),
                            Brand = "Castrol",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Street / commuter / scooter",
                            ProductName = "POWER1 4T 10W-40",
                            Specification = "POWER1 serisi",
                            SubCategory = "4T Sentetik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("e190af3e-bfaf-40c0-82be-7a5af3575d9e"),
                            Brand = "Shell",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Modern 4T motosikletler",
                            ProductName = "Advance Ultra 4T",
                            Specification = "Shell Advance Ultra",
                            SubCategory = "4T Tam Sentetik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("83515191-0df2-cf7f-12a3-d52f7b910981"),
                            Brand = "Liqui Moly",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Street / commuter",
                            ProductName = "Motorbike 4T 10W-40 Street",
                            Specification = "10W-40 Street",
                            SubCategory = "4T Sentetik Teknoloji",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("52a69454-0be6-b474-a4da-d0a606dd9831"),
                            Brand = "Liqui Moly",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ekonomik bakım paketi",
                            ProductName = "10W40 4T Basic Street",
                            Specification = "Basic Street",
                            SubCategory = "4T Mineral / Ekonomik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bb02d709-eff8-29c4-b0c0-c91e04b9a141"),
                            Brand = "IPONE",
                            Category = "Motor Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Roadster / enduro / sportif GT",
                            ProductName = "Full Power Katana 10W-40",
                            Specification = "PAO + ester / 10W-40",
                            SubCategory = "4T Tam Sentetik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("de78a5b9-93b2-5be8-45a0-15e8f31bcb7a"),
                            Brand = "Hiflofiltro",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "HF132",
                            Specification = "Örnek referans",
                            SubCategory = "Spin-on / kartuş",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("00363461-c24b-7560-2dab-7c0d9c1f118c"),
                            Brand = "Hiflofiltro",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "HF204",
                            Specification = "Örnek referans",
                            SubCategory = "Spin-on / kartuş",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("d6fca400-e109-f36e-e8e4-52ec56879daa"),
                            Brand = "Hiflofiltro",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "HF303",
                            Specification = "Örnek referans",
                            SubCategory = "Spin-on / kartuş",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("13b111c6-b411-d084-ac4d-fb0b0e86f8bb"),
                            Brand = "K&N",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "KN-204",
                            Specification = "Örnek referans",
                            SubCategory = "Performance",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("5efc14bb-8123-9ff2-6427-456e3c12c8d2"),
                            Brand = "K&N",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Harley vb. bazı modeller",
                            ProductName = "KN-171B",
                            Specification = "Örnek referans",
                            SubCategory = "Performance",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("8f8ef9dd-855b-cfcb-7382-80f6144f7884"),
                            Brand = "K&N",
                            Category = "Yağ Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "KN-164",
                            Specification = "Örnek referans",
                            SubCategory = "Performance",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f26e49dc-1143-2c40-7f4c-7e14e925a702"),
                            Brand = "Hiflofiltro",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "HFA1134",
                            Specification = "Örnek referans",
                            SubCategory = "OEM replacement",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("138d43e5-0de8-f1bd-91ec-fd71256388fb"),
                            Brand = "Hiflofiltro",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Örn. Forza 250 sınıfı uygulamalar",
                            ProductName = "HFA1304",
                            Specification = "Örnek referans",
                            SubCategory = "OEM replacement",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("0e7d2dc1-6099-390b-5f6e-a01c85f4de11"),
                            Brand = "Hiflofiltro",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Örn. XMAX 250/300 sınıfı uygulamalar",
                            ProductName = "HFA4301",
                            Specification = "Örnek referans",
                            SubCategory = "OEM replacement",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("efd67b80-2d10-9402-7dae-de8cf9a4b1bc"),
                            Brand = "Hiflofiltro",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Örn. KTM 390 Duke sınıfı uygulamalar",
                            ProductName = "HFA6303",
                            Specification = "Örnek referans",
                            SubCategory = "OEM replacement",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("1b7a9a5e-b15f-32f8-a647-206ece844530"),
                            Brand = "K&N",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "KTM uygulamaları dahil performans tipi",
                            ProductName = "KT-1113",
                            Specification = "Örnek referans",
                            SubCategory = "Yıkanabilir / performance",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ab3a82f9-daee-30d6-6ef5-c41d0ff64bc7"),
                            Brand = "K&N",
                            Category = "Hava Filtresi",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "BMW uygulamaları dahil performance tipi",
                            ProductName = "BM-1204",
                            Specification = "Örnek referans",
                            SubCategory = "Yıkanabilir / performance",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ecb44e8e-9693-6500-5016-b715bde61bb9"),
                            Brand = "NGK",
                            Category = "Buji",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Cub / commuter / scooter sınıfında yaygın",
                            ProductName = "CR7HSA",
                            Specification = "Örnek referans",
                            SubCategory = "Standart nikel",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("96f87973-47d5-0915-1c04-ec1de3ec595a"),
                            Brand = "NGK",
                            Category = "Buji",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Scooter / street uygulamaları",
                            ProductName = "CPR8EA-9",
                            Specification = "Örnek referans",
                            SubCategory = "Standart nikel",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("5071ae2e-d029-ca84-a8a9-3b3cbf6bcd92"),
                            Brand = "NGK",
                            Category = "Buji",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Daha uzun ömür / performans",
                            ProductName = "CR9EIX",
                            Specification = "Örnek referans",
                            SubCategory = "İridyum",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("fdf3bd4d-0590-8159-2af3-38740a6ccbf3"),
                            Brand = "Denso",
                            Category = "Buji",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "U24ESR-N",
                            Specification = "Örnek referans",
                            SubCategory = "Standart nikel",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("1aefae80-029a-272f-8f9f-dbeb062d3dc6"),
                            Brand = "Denso",
                            Category = "Buji",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "X24ESR-U",
                            Specification = "Örnek referans",
                            SubCategory = "Standart nikel",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("b5eb00e0-e22e-11ab-3ab9-88d6f3b95074"),
                            Brand = "DID",
                            Category = "Zincir",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Street + off-road upgrade",
                            ProductName = "520VX3",
                            Specification = "520 pitch / VX3",
                            SubCategory = "X-Ring",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("63af54b0-50bc-9768-e595-bf6a12df6e63"),
                            Brand = "DID",
                            Category = "Zincir",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Orta-üst segment street / touring",
                            ProductName = "525VX3",
                            Specification = "525 pitch / VX3",
                            SubCategory = "X-Ring",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("0b6ad96e-757d-ea21-7550-f30dd82dbf2e"),
                            Brand = "RK",
                            Category = "Zincir",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Big-cc / road race / superbike",
                            ProductName = "530 ZXW / GXW serisi",
                            Specification = "XW-Ring",
                            SubCategory = "XW-Ring",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("af7d8707-50ef-b009-375d-4f1b0928a32e"),
                            Brand = "JT Sprockets",
                            Category = "Ön Dişli",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "JTF1586.16RB",
                            Specification = "Örnek referans",
                            SubCategory = "Çelik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("7daefe13-2181-ec14-3ef9-dc2407ab4fce"),
                            Brand = "JT Sprockets",
                            Category = "Arka Dişli",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "JTR300.46",
                            Specification = "Örnek referans",
                            SubCategory = "Çelik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dd6d594b-4522-b458-fa8b-52500faae932"),
                            Brand = "DID + JT",
                            Category = "Zincir + Dişli Set",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "125cc commuter / sport commuter",
                            ProductName = "Did 428D + JT set",
                            Specification = "Örnek kombinasyon",
                            SubCategory = "Komple kit",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f403e4f6-11c2-9782-95cd-c920a19ca889"),
                            Brand = "EBC",
                            Category = "Fren Balatası",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Model bazlı değişir",
                            ProductName = "FA197",
                            Specification = "Örnek referans",
                            SubCategory = "Sinter / ön-arka varyantlı",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("3d8d0387-4617-2cc4-1aae-50f0e67649b2"),
                            Brand = "EBC",
                            Category = "Fren Balatası",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Scooter / street arka uygulamalar",
                            ProductName = "SFA197",
                            Specification = "Örnek referans",
                            SubCategory = "Organik",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f25c6ad6-1d46-3b63-b060-f6795a2e04e1"),
                            Brand = "Brembo",
                            Category = "Fren Balatası",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "All-road / ön balata tarafında yaygın",
                            ProductName = "SA Pads",
                            Specification = "SA bileşimi",
                            SubCategory = "Sinter",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("6f04210e-7035-54e0-a9ac-422fe123b851"),
                            Brand = "SBS",
                            Category = "Fren Balatası",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Scooter / street arka uygulamalar",
                            ProductName = "230HM",
                            Specification = "Örnek referans",
                            SubCategory = "Seramik / street",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("c8ea833f-46de-d68c-1962-4aad66c5f83b"),
                            Brand = "SBS",
                            Category = "Fren Balatası",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Scooter / street arka uygulamalar",
                            ProductName = "155HM",
                            Specification = "Örnek referans",
                            SubCategory = "Seramik / street",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("9f2240b7-5e6d-c3a4-b133-dc73e996b561"),
                            Brand = "NG Brakes",
                            Category = "Fren Diski",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ön / arka disk",
                            ProductName = "Genel seri",
                            Specification = "Modele göre referans değişir",
                            SubCategory = "Round / fixed / floating",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f2cf18df-2726-488f-2748-d6455fde56e7"),
                            Brand = "Brembo",
                            Category = "Fren Diski",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Premium replacement",
                            ProductName = "Serie Oro",
                            Specification = "Fixed / floating seçenekleri",
                            SubCategory = "Serie Oro",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("42142bf6-ef47-3974-e9b9-f4a05fdf070e"),
                            Brand = "Motul",
                            Category = "Fren Hidroliği",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Standart bakım / fren & debriyaj hidrolik sistemleri",
                            ProductName = "DOT 3&4 Brake Fluid",
                            Specification = "0.5L",
                            SubCategory = "DOT 3/4",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("704e5406-b386-6fa1-4cbc-95511ecdae99"),
                            Brand = "Motul",
                            Category = "Fren Hidroliği",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "ABS/ESP uyumlu sistemler dahil",
                            ProductName = "DOT 4 LV",
                            Specification = "Class 6 / düşük viskozite",
                            SubCategory = "DOT 4 LV",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("e5dece29-227d-a4cb-c172-ab868e91e321"),
                            Brand = "Motul",
                            Category = "Fren Hidroliği",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Yüksek sıcaklık / performans",
                            ProductName = "RBF 660 Factory Line",
                            Specification = "0.5L",
                            SubCategory = "Racing",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("d7147fdd-50d5-0a3e-1274-10c62eb585a4"),
                            Brand = "Liqui Moly",
                            Category = "Fren Hidroliği",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Standart bakım",
                            ProductName = "Brake Fluid DOT 4 (3093)",
                            Specification = "500 ml",
                            SubCategory = "DOT 4",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ca4c7dce-4467-13fa-fd01-b718f77d21a2"),
                            Brand = "Liqui Moly",
                            Category = "Fren Hidroliği",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "ABS'li sistemlerde tercih edilebilir",
                            ProductName = "Brake Fluid SL6 DOT 4 (21167)",
                            Specification = "500 ml",
                            SubCategory = "DOT 4 düşük viskozite",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("967af2a5-0233-d780-f8b3-e9f22240ed0e"),
                            Brand = "Motul",
                            Category = "Soğutma Sıvısı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Sıvı soğutmalı motosikletler",
                            ProductName = "Motocool Factory Line -35C",
                            Specification = "1L / Organic+",
                            SubCategory = "Hazır kullanım",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("25b6e6de-d73a-d1ec-a68c-38636424831b"),
                            Brand = "Motorex",
                            Category = "Soğutma Sıvısı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Alüminyum motorlarda yaygın premium seçenek",
                            ProductName = "Coolant M3.0",
                            Specification = "1L / OAT ready to use",
                            SubCategory = "Hazır kullanım",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("6f76b8e8-87eb-002e-cb96-b1de531c22b4"),
                            Brand = "Motul",
                            Category = "Fork Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ön maşa bakımında",
                            ProductName = "Fork Oil Expert 5W",
                            Specification = "5W / 1L",
                            SubCategory = "Suspension oil",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("86707dd5-c92e-6157-f5b3-7b2e7119ccc3"),
                            Brand = "Motul",
                            Category = "Fork Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ön maşa bakımında",
                            ProductName = "Fork Oil Expert 10W",
                            Specification = "10W / 1L",
                            SubCategory = "Suspension oil",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f5df91d1-93fe-447f-dae4-5d96848c4c52"),
                            Brand = "Motul",
                            Category = "Fork Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ağır sönümleme isteyen uygulamalar",
                            ProductName = "Fork Oil Expert 20W",
                            Specification = "20W / 1L",
                            SubCategory = "Suspension oil",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("f4a3c123-7858-f34d-c49b-d387e8173f12"),
                            Brand = "Motorex",
                            Category = "Fork Yağı",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Ön maşa bakımında premium seçenek",
                            ProductName = "Racing Fork Oil 5W",
                            Specification = "5W / 1L",
                            SubCategory = "Suspension oil",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("c041a07e-26f8-7f39-c132-4fdd54c71356"),
                            Brand = "Yuasa",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Scooter / 125-300cc sınıfında sık görülür",
                            ProductName = "YTX7L-BS",
                            Specification = "12V 6Ah 100 CCA",
                            SubCategory = "AGM / MF",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("e25c0545-37aa-10aa-8411-d30a8c56f58e"),
                            Brand = "Yuasa",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Orta segment street / touring",
                            ProductName = "YTX12-BS",
                            Specification = "12V 10Ah 180 CCA",
                            SubCategory = "AGM / MF",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("9f03da2b-6355-2621-09e8-88c2be019f9f"),
                            Brand = "Yuasa",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Orta-üst segment",
                            ProductName = "YTX14-BS",
                            Specification = "12V 12.6Ah",
                            SubCategory = "AGM / MF",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("06024250-45c8-444f-2e15-7d845275336e"),
                            Brand = "Yuasa",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Sport / naked / scooter uygulamaları",
                            ProductName = "YTZ10S",
                            Specification = "12V 9.1Ah 190 CCA",
                            SubCategory = "AGM / MF",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44c385c7-ab87-e673-a965-5efb37ceadb7"),
                            Brand = "BS Battery",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "125-300cc sınıfında yaygın alternatif",
                            ProductName = "BTX7L-BS",
                            Specification = "12V 6.3Ah 100A EN",
                            SubCategory = "SLA / MF",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("78ab1c51-b99f-6345-f9c1-fc5ef7be5588"),
                            Brand = "BS Battery",
                            Category = "Akü",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSystemDefault = true,
                            Notes = "Orta segment street / touring",
                            ProductName = "BTZ10S",
                            Specification = "12V 9Ah 190A EN",
                            SubCategory = "SLA / MF",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Complaint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("LaborTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PaidTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PartsTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleKm")
                        .HasColumnType("integer");

                    b.Property<string>("WorkDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OrderNo")
                        .IsUnique();

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrderAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("ServiceOrderAttachments", (string)null);
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("ServiceOrderStatusHistories");
                });

            modelBuilder.Entity("MotorCare.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("TRY");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("DefaultPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("ServiceCatalogItems");
                });

            modelBuilder.Entity("MotorCare.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MotorCare.Domain.Users.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("MotorCare.Domain.Users.Entities.UserSecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Purpose", "CreatedAt");

                    b.ToTable("UserSecurityTokens");
                });

            modelBuilder.Entity("MotorCare.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorProvider")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotorCare.Domain.Vehicles.MotorcycleModelCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("BrandNormalized")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EngineCc")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ModelFamily")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ModelNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("OriginRegion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Segment")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("IsActive");

                    b.HasIndex("OriginCountry");

                    b.HasIndex("Segment");

                    b.HasIndex("Brand", "Model");

                    b.HasIndex("BrandNormalized", "ModelNormalized")
                        .IsUnique();

                    b.ToTable("MotorcycleModelCatalogItems", (string)null);
                });

            modelBuilder.Entity("MotorCare.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentCustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentKm")
                        .HasColumnType("integer");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MotorCare.Infrastructure.Persistence.Entities.ServiceOrderNumberCounter", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CounterDate")
                        .HasColumnType("date");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "CounterDate");

                    b.ToTable("ServiceOrderNumberCounters", (string)null);
                });

            modelBuilder.Entity("MotorCare.Domain.Inspections.MotorcycleInspection", b =>
                {
                    b.OwnsMany("MotorCare.Domain.Inspections.Entities.MotorcycleInspectionItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("MotorcycleInspectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("MotorcycleInspectionId");

                            b1.ToTable("MotorcycleInspectionItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleInspectionId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.OwnsMany("MotorCare.Domain.ServiceOrders.Entities.ServiceConsumableItem", "Consumables", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Notes")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Specification")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<string>("SubCategory")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ServiceOrderId");

                            b1.ToTable("ServiceConsumableItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsMany("MotorCare.Domain.ServiceOrders.Entities.ServiceOperationItem", "Operations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ServiceOrderId");

                            b1.ToTable("ServiceOperationItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsMany("MotorCare.Domain.ServiceOrders.Entities.ServicePartItem", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("PartName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PartNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ServiceOrderId");

                            b1.ToTable("ServicePartItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsMany("MotorCare.Domain.ServiceOrders.Entities.ServicePayment", "Payments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<DateTimeOffset>("PaymentDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ServiceOrderId");

                            b1.ToTable("ServicePayments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.Navigation("Consumables");

                    b.Navigation("Operations");

                    b.Navigation("Parts");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrderAttachment", b =>
                {
                    b.HasOne("MotorCare.Domain.ServiceOrders.ServiceOrder", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrderStatusHistory", b =>
                {
                    b.HasOne("MotorCare.Domain.ServiceOrders.ServiceOrder", null)
                        .WithMany()
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorCare.Domain.Users.Entities.RefreshToken", b =>
                {
                    b.HasOne("MotorCare.Domain.Users.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorCare.Domain.Users.Entities.UserSecurityToken", b =>
                {
                    b.HasOne("MotorCare.Domain.Users.User", null)
                        .WithMany("SecurityTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorCare.Domain.Vehicles.Vehicle", b =>
                {
                    b.OwnsOne("MotorCare.Domain.ValueObjects.PlateNumber", "Plate", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PlateNormalized");

                            b1.Property<string>("OriginalValue")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PlateOriginal");

                            b1.HasKey("VehicleId");

                            b1.HasIndex("NormalizedValue")
                                .HasDatabaseName("IX_Vehicles_PlateNormalized");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsMany("MotorCare.Domain.Vehicles.Entities.VehicleNote", "Notes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VehicleId");

                            b1.ToTable("VehicleNotes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsMany("MotorCare.Domain.Vehicles.Entities.VehiclePhoto", "Photos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("PhotoUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VehicleId");

                            b1.ToTable("VehiclePhotos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("Notes");

                    b.Navigation("Photos");

                    b.Navigation("Plate")
                        .IsRequired();
                });

            modelBuilder.Entity("MotorCare.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MotorCare.Domain.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("SecurityTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
