namespace MotorCare.Infrastructure.Persistence.Seed;

public static class MotorcycleModelCatalogDefaults
{
    public static IReadOnlyList<MotorcycleModelCatalogSeedItem> Items { get; } =
    [
        Seed("Honda", "PCX 125", "PCX", "Scooter", 125, "Japan", "Asia"),
        Seed("Honda", "Forza 250", "Forza", "Maxi Scooter", 250, "Japan", "Asia"),
        Seed("Honda", "Forza 350", "Forza", "Maxi Scooter", 350, "Japan", "Asia"),
        Seed("Honda", "ADV350", "ADV", "Adventure Scooter", 350, "Japan", "Asia"),
        Seed("Honda", "CB125R", "CB", "Naked", 125, "Japan", "Asia"),
        Seed("Honda", "CB250R", "CB", "Naked", 250, "Japan", "Asia"),
        Seed("Honda", "CB500F", "CB", "Naked", 500, "Japan", "Asia"),
        Seed("Honda", "CB500X", "CB", "Adventure", 500, "Japan", "Asia"),
        Seed("Honda", "NX500", "NX", "Adventure", 500, "Japan", "Asia"),
        Seed("Honda", "CB650R", "CB", "Naked", 650, "Japan", "Asia"),
        Seed("Honda", "CBR650R", "CBR", "Sport", 650, "Japan", "Asia"),
        Seed("Honda", "CB750 Hornet", "CB", "Naked", 750, "Japan", "Asia"),
        Seed("Honda", "XL750 Transalp", "XL", "Adventure", 750, "Japan", "Asia"),
        Seed("Honda", "CRF300L", "CRF", "Dual Sport", 300, "Japan", "Asia"),
        Seed("Honda", "Africa Twin CRF1100L", "Africa Twin", "Adventure", 1100, "Japan", "Asia"),
        Seed("Honda", "NT1100", "NT", "Sport Touring", 1100, "Japan", "Asia"),
        Seed("Honda", "Gold Wing GL1800", "Gold Wing", "Touring", 1800, "Japan", "Asia"),

        Seed("Yamaha", "NMAX 125", "NMAX", "Scooter", 125, "Japan", "Asia"),
        Seed("Yamaha", "NMAX 155", "NMAX", "Scooter", 155, "Japan", "Asia"),
        Seed("Yamaha", "XMAX 250", "XMAX", "Maxi Scooter", 250, "Japan", "Asia"),
        Seed("Yamaha", "XMAX 300", "XMAX", "Maxi Scooter", 300, "Japan", "Asia"),
        Seed("Yamaha", "MT-07", "MT", "Naked", 700, "Japan", "Asia"),
        Seed("Yamaha", "MT-09", "MT", "Naked", 900, "Japan", "Asia"),
        Seed("Yamaha", "MT-10", "MT", "Naked", 1000, "Japan", "Asia"),
        Seed("Yamaha", "R125", "R", "Sport", 125, "Japan", "Asia"),
        Seed("Yamaha", "R3", "R", "Sport", 320, "Japan", "Asia"),
        Seed("Yamaha", "R7", "R", "Sport", 690, "Japan", "Asia"),
        Seed("Yamaha", "R1", "R", "Sport", 1000, "Japan", "Asia"),
        Seed("Yamaha", "Tracer 7", "Tracer", "Sport Touring", 700, "Japan", "Asia"),
        Seed("Yamaha", "Tracer 9", "Tracer", "Sport Touring", 900, "Japan", "Asia"),
        Seed("Yamaha", "Tenere 700", "Tenere", "Adventure", 700, "Japan", "Asia"),
        Seed("Yamaha", "XSR700", "XSR", "Modern Classic", 700, "Japan", "Asia"),
        Seed("Yamaha", "XSR900", "XSR", "Modern Classic", 900, "Japan", "Asia"),
        Seed("Yamaha", "RayZR", "RayZR", "Scooter", 125, "Japan", "Asia"),
        Seed("Yamaha", "Tricity 300", "Tricity", "Three-Wheeler", 300, "Japan", "Asia"),

        Seed("Kawasaki", "Ninja 400", "Ninja", "Sport", 400, "Japan", "Asia"),
        Seed("Kawasaki", "Ninja 500", "Ninja", "Sport", 500, "Japan", "Asia"),
        Seed("Kawasaki", "Ninja 650", "Ninja", "Sport", 650, "Japan", "Asia"),
        Seed("Kawasaki", "Ninja ZX-4R", "Ninja ZX", "Sport", 400, "Japan", "Asia"),
        Seed("Kawasaki", "Ninja ZX-6R", "Ninja ZX", "Sport", 636, "Japan", "Asia"),
        Seed("Kawasaki", "Ninja ZX-10R", "Ninja ZX", "Sport", 1000, "Japan", "Asia"),
        Seed("Kawasaki", "Z400", "Z", "Naked", 400, "Japan", "Asia"),
        Seed("Kawasaki", "Z500", "Z", "Naked", 500, "Japan", "Asia"),
        Seed("Kawasaki", "Z650", "Z", "Naked", 650, "Japan", "Asia"),
        Seed("Kawasaki", "Z900", "Z", "Naked", 900, "Japan", "Asia"),
        Seed("Kawasaki", "Z H2", "Z", "Naked", 1000, "Japan", "Asia"),
        Seed("Kawasaki", "Versys 650", "Versys", "Adventure Touring", 650, "Japan", "Asia"),
        Seed("Kawasaki", "Versys 1000", "Versys", "Adventure Touring", 1000, "Japan", "Asia"),
        Seed("Kawasaki", "Vulcan S", "Vulcan", "Cruiser", 650, "Japan", "Asia"),
        Seed("Kawasaki", "Eliminator 500", "Eliminator", "Cruiser", 500, "Japan", "Asia"),

        Seed("Suzuki", "GSX-R125", "GSX-R", "Sport", 125, "Japan", "Asia"),
        Seed("Suzuki", "GSX-S125", "GSX-S", "Naked", 125, "Japan", "Asia"),
        Seed("Suzuki", "GSX-8S", "GSX", "Naked", 800, "Japan", "Asia"),
        Seed("Suzuki", "GSX-8R", "GSX", "Sport", 800, "Japan", "Asia"),
        Seed("Suzuki", "GSX-S1000", "GSX-S", "Naked", 1000, "Japan", "Asia"),
        Seed("Suzuki", "GSX-S1000GT", "GSX-S", "Sport Touring", 1000, "Japan", "Asia"),
        Seed("Suzuki", "GSX-S1000GX", "GSX-S", "Crossover", 1000, "Japan", "Asia"),
        Seed("Suzuki", "Hayabusa", "Hayabusa", "Sport Touring", 1340, "Japan", "Asia"),
        Seed("Suzuki", "V-Strom 650", "V-Strom", "Adventure", 650, "Japan", "Asia"),
        Seed("Suzuki", "V-Strom 800", "V-Strom", "Adventure", 800, "Japan", "Asia"),
        Seed("Suzuki", "V-Strom 800 DE", "V-Strom", "Adventure", 800, "Japan", "Asia"),
        Seed("Suzuki", "V-Strom 1050 DE", "V-Strom", "Adventure", 1050, "Japan", "Asia"),
        Seed("Suzuki", "Burgman 400", "Burgman", "Maxi Scooter", 400, "Japan", "Asia"),
        Seed("Suzuki", "DR-Z4S", "DR-Z", "Dual Sport", 400, "Japan", "Asia"),
        Seed("Suzuki", "DR-Z4SM", "DR-Z", "Supermoto", 400, "Japan", "Asia"),

        Seed("BMW", "G 310 R", "G", "Naked", 310, "Germany", "Europe"),
        Seed("BMW", "G 310 GS", "G", "Adventure", 310, "Germany", "Europe"),
        Seed("BMW", "F 800 GS", "F", "Adventure", 800, "Germany", "Europe"),
        Seed("BMW", "F 900 GS", "F", "Adventure", 900, "Germany", "Europe"),
        Seed("BMW", "F 900 GS Adventure", "F", "Adventure", 900, "Germany", "Europe"),
        Seed("BMW", "F 900 R", "F", "Naked", 900, "Germany", "Europe"),
        Seed("BMW", "F 900 XR", "F", "Sport Touring", 900, "Germany", "Europe"),
        Seed("BMW", "R 12", "R", "Cruiser", 1200, "Germany", "Europe"),
        Seed("BMW", "R 12 nineT", "R", "Modern Classic", 1200, "Germany", "Europe"),
        Seed("BMW", "R 18", "R", "Cruiser", 1800, "Germany", "Europe"),
        Seed("BMW", "R 1250 GS", "R", "Adventure", 1250, "Germany", "Europe"),
        Seed("BMW", "R 1300 GS", "R", "Adventure", 1300, "Germany", "Europe"),
        Seed("BMW", "R 1300 GS Adventure", "R", "Adventure", 1300, "Germany", "Europe"),
        Seed("BMW", "S 1000 RR", "S", "Sport", 1000, "Germany", "Europe"),
        Seed("BMW", "S 1000 R", "S", "Naked", 1000, "Germany", "Europe"),
        Seed("BMW", "S 1000 XR", "S", "Sport Touring", 1000, "Germany", "Europe"),
        Seed("BMW", "M 1000 RR", "M", "Sport", 1000, "Germany", "Europe"),
        Seed("BMW", "C 400 X", "C", "Scooter", 400, "Germany", "Europe"),
        Seed("BMW", "C 400 GT", "C", "Scooter", 400, "Germany", "Europe"),
        Seed("BMW", "CE 04", "CE", "Electric Scooter", null, "Germany", "Europe"),

        Seed("Ducati", "Scrambler Icon", "Scrambler", "Modern Classic", 800, "Italy", "Europe"),
        Seed("Ducati", "Monster", "Monster", "Naked", 937, "Italy", "Europe"),
        Seed("Ducati", "Hypermotard 950", "Hypermotard", "Supermoto", 950, "Italy", "Europe"),
        Seed("Ducati", "Multistrada V2", "Multistrada", "Adventure Touring", 950, "Italy", "Europe"),
        Seed("Ducati", "Multistrada V4", "Multistrada", "Adventure Touring", 1158, "Italy", "Europe"),
        Seed("Ducati", "DesertX", "DesertX", "Adventure", 937, "Italy", "Europe"),
        Seed("Ducati", "Panigale V2", "Panigale", "Sport", 955, "Italy", "Europe"),
        Seed("Ducati", "Panigale V4", "Panigale", "Sport", 1100, "Italy", "Europe"),
        Seed("Ducati", "Streetfighter V2", "Streetfighter", "Naked", 955, "Italy", "Europe"),
        Seed("Ducati", "Streetfighter V4", "Streetfighter", "Naked", 1100, "Italy", "Europe"),
        Seed("Ducati", "Diavel V4", "Diavel", "Power Cruiser", 1158, "Italy", "Europe"),
        Seed("Ducati", "XDiavel", "XDiavel", "Cruiser", 1260, "Italy", "Europe"),

        Seed("Triumph", "Speed 400", "Speed", "Naked", 400, "United Kingdom", "Europe"),
        Seed("Triumph", "Scrambler 400 X", "Scrambler", "Scrambler", 400, "United Kingdom", "Europe"),
        Seed("Triumph", "Trident 660", "Trident", "Naked", 660, "United Kingdom", "Europe"),
        Seed("Triumph", "Tiger Sport 660", "Tiger", "Sport Touring", 660, "United Kingdom", "Europe"),
        Seed("Triumph", "Tiger 850 Sport", "Tiger", "Adventure Touring", 850, "United Kingdom", "Europe"),
        Seed("Triumph", "Tiger 900 GT", "Tiger", "Adventure Touring", 900, "United Kingdom", "Europe"),
        Seed("Triumph", "Tiger 900 Rally Pro", "Tiger", "Adventure Touring", 900, "United Kingdom", "Europe"),
        Seed("Triumph", "Tiger 1200 GT", "Tiger", "Adventure Touring", 1200, "United Kingdom", "Europe"),
        Seed("Triumph", "Street Triple 765", "Street Triple", "Naked", 765, "United Kingdom", "Europe"),
        Seed("Triumph", "Speed Triple 1200", "Speed Triple", "Naked", 1200, "United Kingdom", "Europe"),
        Seed("Triumph", "Bonneville T100", "Bonneville", "Modern Classic", 900, "United Kingdom", "Europe"),
        Seed("Triumph", "Bonneville T120", "Bonneville", "Modern Classic", 1200, "United Kingdom", "Europe"),
        Seed("Triumph", "Scrambler 900", "Scrambler", "Scrambler", 900, "United Kingdom", "Europe"),
        Seed("Triumph", "Scrambler 1200", "Scrambler", "Scrambler", 1200, "United Kingdom", "Europe"),

        Seed("KTM", "125 Duke", "Duke", "Naked", 125, "Austria", "Europe"),
        Seed("KTM", "250 Duke", "Duke", "Naked", 250, "Austria", "Europe"),
        Seed("KTM", "390 Duke", "Duke", "Naked", 390, "Austria", "Europe"),
        Seed("KTM", "790 Duke", "Duke", "Naked", 790, "Austria", "Europe"),
        Seed("KTM", "890 Duke", "Duke", "Naked", 890, "Austria", "Europe"),
        Seed("KTM", "990 Duke", "Duke", "Naked", 990, "Austria", "Europe"),
        Seed("KTM", "1390 Super Duke R", "Super Duke", "Naked", 1390, "Austria", "Europe"),
        Seed("KTM", "RC 390", "RC", "Sport", 390, "Austria", "Europe"),
        Seed("KTM", "390 Adventure", "Adventure", "Adventure", 390, "Austria", "Europe"),
        Seed("KTM", "790 Adventure", "Adventure", "Adventure", 790, "Austria", "Europe"),
        Seed("KTM", "890 Adventure", "Adventure", "Adventure", 890, "Austria", "Europe"),
        Seed("KTM", "1290 Super Adventure", "Super Adventure", "Adventure", 1290, "Austria", "Europe"),
        Seed("KTM", "450 EXC-F", "EXC", "Enduro", 450, "Austria", "Europe"),
        Seed("KTM", "500 EXC-F", "EXC", "Enduro", 500, "Austria", "Europe"),

        Seed("Husqvarna", "Svartpilen 125", "Svartpilen", "Naked", 125, "Sweden", "Europe"),
        Seed("Husqvarna", "Svartpilen 250", "Svartpilen", "Naked", 250, "Sweden", "Europe"),
        Seed("Husqvarna", "Svartpilen 401", "Svartpilen", "Naked", 401, "Sweden", "Europe"),
        Seed("Husqvarna", "Vitpilen 401", "Vitpilen", "Naked", 401, "Sweden", "Europe"),
        Seed("Husqvarna", "Norden 901", "Norden", "Adventure", 901, "Sweden", "Europe"),
        Seed("Husqvarna", "FE 250", "FE", "Enduro", 250, "Sweden", "Europe"),
        Seed("Husqvarna", "FE 350", "FE", "Enduro", 350, "Sweden", "Europe"),
        Seed("Husqvarna", "FE 501", "FE", "Enduro", 501, "Sweden", "Europe"),

        Seed("Aprilia", "SR GT 200", "SR GT", "Scooter", 200, "Italy", "Europe"),
        Seed("Aprilia", "Tuono 125", "Tuono", "Naked", 125, "Italy", "Europe"),
        Seed("Aprilia", "RS 125", "RS", "Sport", 125, "Italy", "Europe"),
        Seed("Aprilia", "RS 457", "RS", "Sport", 457, "Italy", "Europe"),
        Seed("Aprilia", "Tuono 660", "Tuono", "Naked", 660, "Italy", "Europe"),
        Seed("Aprilia", "RS 660", "RS", "Sport", 660, "Italy", "Europe"),
        Seed("Aprilia", "Tuareg 660", "Tuareg", "Adventure", 660, "Italy", "Europe"),
        Seed("Aprilia", "RSV4", "RSV", "Sport", 1100, "Italy", "Europe"),
        Seed("Aprilia", "Tuono V4", "Tuono", "Naked", 1100, "Italy", "Europe"),

        Seed("Moto Guzzi", "V7 Stone", "V7", "Modern Classic", 850, "Italy", "Europe"),
        Seed("Moto Guzzi", "V7 Special", "V7", "Modern Classic", 850, "Italy", "Europe"),
        Seed("Moto Guzzi", "V85 TT", "V85", "Adventure Touring", 850, "Italy", "Europe"),
        Seed("Moto Guzzi", "V100 Mandello", "V100", "Sport Touring", 1042, "Italy", "Europe"),

        Seed("Piaggio", "Beverly 300", "Beverly", "Scooter", 300, "Italy", "Europe"),
        Seed("Piaggio", "Beverly 400", "Beverly", "Scooter", 400, "Italy", "Europe"),
        Seed("Piaggio", "Medley 150", "Medley", "Scooter", 150, "Italy", "Europe"),
        Seed("Piaggio", "MP3 300", "MP3", "Three-Wheeler", 300, "Italy", "Europe"),
        Seed("Piaggio", "MP3 400", "MP3", "Three-Wheeler", 400, "Italy", "Europe"),
        Seed("Piaggio", "MP3 530", "MP3", "Three-Wheeler", 530, "Italy", "Europe"),

        Seed("Vespa", "Primavera 125", "Primavera", "Scooter", 125, "Italy", "Europe"),
        Seed("Vespa", "Primavera 150", "Primavera", "Scooter", 150, "Italy", "Europe"),
        Seed("Vespa", "Sprint 125", "Sprint", "Scooter", 125, "Italy", "Europe"),
        Seed("Vespa", "Sprint 150", "Sprint", "Scooter", 150, "Italy", "Europe"),
        Seed("Vespa", "GTS 300", "GTS", "Scooter", 300, "Italy", "Europe"),
        Seed("Vespa", "GTV 300", "GTV", "Scooter", 300, "Italy", "Europe"),

        Seed("MV Agusta", "Brutale 800", "Brutale", "Naked", 800, "Italy", "Europe"),
        Seed("MV Agusta", "Dragster 800", "Dragster", "Naked", 800, "Italy", "Europe"),
        Seed("MV Agusta", "Turismo Veloce", "Turismo Veloce", "Sport Touring", 800, "Italy", "Europe"),
        Seed("MV Agusta", "Superveloce 800", "Superveloce", "Sport", 800, "Italy", "Europe"),

        Seed("Harley-Davidson", "Nightster", "Nightster", "Cruiser", 975, "United States", "North America"),
        Seed("Harley-Davidson", "Nightster Special", "Nightster", "Cruiser", 975, "United States", "North America"),
        Seed("Harley-Davidson", "Sportster S", "Sportster", "Cruiser", 1250, "United States", "North America"),
        Seed("Harley-Davidson", "Pan America 1250", "Pan America", "Adventure", 1250, "United States", "North America"),
        Seed("Harley-Davidson", "Pan America 1250 Special", "Pan America", "Adventure", 1250, "United States", "North America"),
        Seed("Harley-Davidson", "Street Bob", "Softail", "Cruiser", 1868, "United States", "North America"),
        Seed("Harley-Davidson", "Fat Bob", "Softail", "Cruiser", 1868, "United States", "North America"),
        Seed("Harley-Davidson", "Fat Boy", "Softail", "Cruiser", 1868, "United States", "North America"),
        Seed("Harley-Davidson", "Low Rider S", "Softail", "Cruiser", 1923, "United States", "North America"),
        Seed("Harley-Davidson", "Low Rider ST", "Softail", "Cruiser", 1923, "United States", "North America"),
        Seed("Harley-Davidson", "Breakout", "Softail", "Cruiser", 1923, "United States", "North America"),
        Seed("Harley-Davidson", "Street Glide", "Touring", "Touring", 1923, "United States", "North America"),
        Seed("Harley-Davidson", "Road Glide", "Touring", "Touring", 1923, "United States", "North America"),
        Seed("Harley-Davidson", "Road King Special", "Touring", "Touring", 1868, "United States", "North America"),

        Seed("Indian Motorcycle", "Scout", "Scout", "Cruiser", 1133, "United States", "North America"),
        Seed("Indian Motorcycle", "Scout Bobber", "Scout", "Cruiser", 1133, "United States", "North America"),
        Seed("Indian Motorcycle", "Chief", "Chief", "Cruiser", 1890, "United States", "North America"),
        Seed("Indian Motorcycle", "Sport Chief", "Chief", "Cruiser", 1890, "United States", "North America"),
        Seed("Indian Motorcycle", "Super Chief", "Chief", "Cruiser", 1890, "United States", "North America"),
        Seed("Indian Motorcycle", "FTR", "FTR", "Naked", 1203, "United States", "North America"),
        Seed("Indian Motorcycle", "Chieftain", "Chieftain", "Touring", 1890, "United States", "North America"),
        Seed("Indian Motorcycle", "Challenger", "Challenger", "Touring", 1768, "United States", "North America"),
        Seed("Indian Motorcycle", "Roadmaster", "Roadmaster", "Touring", 1890, "United States", "North America"),

        Seed("Royal Enfield", "Hunter 350", "Hunter", "Modern Classic", 350, "India", "Asia"),
        Seed("Royal Enfield", "Classic 350", "Classic", "Modern Classic", 350, "India", "Asia"),
        Seed("Royal Enfield", "Meteor 350", "Meteor", "Cruiser", 350, "India", "Asia"),
        Seed("Royal Enfield", "Himalayan", "Himalayan", "Adventure", 411, "India", "Asia"),
        Seed("Royal Enfield", "Himalayan 450", "Himalayan", "Adventure", 450, "India", "Asia"),
        Seed("Royal Enfield", "Scram 411", "Scram", "Scrambler", 411, "India", "Asia"),
        Seed("Royal Enfield", "Interceptor 650", "Interceptor", "Modern Classic", 650, "India", "Asia"),
        Seed("Royal Enfield", "Continental GT 650", "Continental GT", "Cafe Racer", 650, "India", "Asia"),
        Seed("Royal Enfield", "Super Meteor 650", "Super Meteor", "Cruiser", 650, "India", "Asia"),
        Seed("Royal Enfield", "Shotgun 650", "Shotgun", "Cruiser", 650, "India", "Asia")
    ];

    private static MotorcycleModelCatalogSeedItem Seed(
        string brand,
        string model,
        string? family,
        string? segment,
        int? engineCc,
        string? originCountry,
        string? originRegion)
        => new(brand, model, family, segment, engineCc, originCountry, originRegion);
}

public sealed record MotorcycleModelCatalogSeedItem(
    string Brand,
    string Model,
    string? ModelFamily,
    string? Segment,
    int? EngineCc,
    string? OriginCountry,
    string? OriginRegion);
